// Maps bookmaker IDs (lowercase, as returned by SportsGameOdds API) to their homepage URLs.
const SPORTSBOOK_LINKS = {
  draftkings: 'https://sportsbook.draftkings.com',
  fanduel: 'https://sportsbook.fanduel.com',
  betmgm: 'https://sports.betmgm.com',
  caesars: 'https://www.caesars.com/sportsbook-and-casino',
  espnbet: 'https://espnbet.com',
  fanatics: 'https://sportsbook.fanatics.com',
  bet365: 'https://www.bet365.com',
  betrivers: 'https://www.betrivers.com',
  hardrockbet: 'https://app.hardrock.bet',
  unibet: 'https://www.unibet.com',
  pointsbet: 'https://www.pointsbet.com',
  wynnbet: 'https://www.wynnbet.com',
  circa: 'https://www.circasports.com',
  bovada: 'https://www.bovada.lv',
  mybookie: 'https://www.mybookie.ag',
  betonline: 'https://www.betonline.ag',
  barstoolsportsbook: 'https://www.barstoolsportsbook.com',
  thescorebet: 'https://www.thescore.bet',
  betway: 'https://www.betway.com',
  '888sport': 'https://www.888sport.com',
  bwin: 'https://sports.bwin.com',
  williamhill: 'https://www.williamhill.com',
  ladbrokes: 'https://www.ladbrokes.com',
  paddypower: 'https://www.paddypower.com',
  skybet: 'https://www.skybet.com',
  betfred: 'https://www.betfred.com',
  tab: 'https://www.tab.com.au',
  sportsbet: 'https://www.sportsbet.com.au',
  playup: 'https://www.playup.com',
  lowvig: 'https://www.lowvig.ag',
  heritage: 'https://www.heritagesports.eu',
  bookmaker: 'https://www.bookmaker.eu',
  jazzsports: 'https://www.jazzsports.ag',
  betdsi: 'https://www.betdsi.eu',
  youwager: 'https://www.youwager.lv',
  intertops: 'https://www.everygame.eu',
  pinnacle: 'https://www.pinnacle.com',
  matchbook: 'https://www.matchbook.com',
  betanysports: 'https://www.betanysports.eu',
  betus: 'https://www.betus.com.pa',
  gtbets: 'https://www.gtbets.eu',
  bet105: 'https://www.bet105.com',
  fliff: 'https://www.getfliff.com',
  underdog: 'https://underdogfantasy.com',
  prizepicks: 'https://www.prizepicks.com',
  novig: 'https://www.novig.com',
  polymarket: 'https://polymarket.com',
  kalshi: 'https://kalshi.com',
  betfairexchange: 'https://www.betfair.com/exchange',
  prophetexchange: 'https://www.prophetexchange.com',
  sporttrade: 'https://sporttrade.com',
}

export function getSportsbookUrl(bookId) {
  if (!bookId) return null
  return SPORTSBOOK_LINKS[bookId.toLowerCase()] || null
}

export default SPORTSBOOK_LINKS
